package ui;

import java.awt.Color;

import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prince
 * 
 * 
 */

class NewPopUpFrame extends javax.swing.JFrame{
    
}
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	setTitle("Load Balancing of VMs in a cluster");
    	setDefaultLookAndFeelDecorated(true);
    
        buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JRadioButton addhost = new javax.swing.JRadioButton();
        runlba = new javax.swing.JRadioButton();
        addvm = new javax.swing.JRadioButton();
        poweron = new javax.swing.JRadioButton();
        poweroff = new javax.swing.JRadioButton();
        showstatus = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup.add(addhost);
        addhost.setText("Add Host");
        addhost.setBorderPainted(true);
        addhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhostActionPerformed(evt);
            }
        });

        buttonGroup.add(runlba);
        runlba.setText("Load Balance");
        runlba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runlbaActionPerformed(evt);
            }
        });

        buttonGroup.add(addvm);
        addvm.setText("Add VM");
        addvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvmActionPerformed(evt);
            }
        });

        buttonGroup.add(poweron);
        poweron.setText("Power On");
        poweron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poweronActionPerformed(evt);
            }
        });

        buttonGroup.add(poweroff);
        poweroff.setText("Power Off");
        poweroff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poweroffActionPerformed(evt);
            }
        });

        buttonGroup.add(showstatus);
        showstatus.setText("Show Status");
        showstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addhost)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poweron)
                            .addComponent(addvm)
                            .addComponent(poweroff)
                            .addComponent(runlba)
                            .addComponent(showstatus))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(addhost)
                .addGap(17, 17, 17)
                .addComponent(addvm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(poweron)
                .addGap(7, 7, 7)
                .addComponent(poweroff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runlba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showstatus)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        addhost.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhostActionPerformed

        // TODO add your handling code here:
        AddHost n=new AddHost();
        n.setVisible(true);
    }//GEN-LAST:event_addhostActionPerformed

    private void runlbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runlbaActionPerformed
        // TODO add your handling code here:
        
        LoadBalance l=new LoadBalance();
        l.setVisible(true);
    }//GEN-LAST:event_runlbaActionPerformed

    private void addvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvmActionPerformed
        // TODO add your handling code here:
        
        AddVm av=new AddVm();
        av.setVisible(true);
    }//GEN-LAST:event_addvmActionPerformed

    private void poweronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poweronActionPerformed
//        poweron po=new poweron();
//        po.setVisible(true);
        new PowerOn();
    }//GEN-LAST:event_poweronActionPerformed

    private void poweroffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poweroffActionPerformed
        new PowerOff();
    }//GEN-LAST:event_poweroffActionPerformed

    private void showstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showstatusActionPerformed
       Status s=new Status();
        s.setVisible(true);
    }//GEN-LAST:event_showstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addvm;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton poweroff;
    private javax.swing.JRadioButton poweron;
    private javax.swing.JRadioButton runlba;
    private javax.swing.JRadioButton showstatus;
    // End of variables declaration//GEN-END:variables
}
